language: elixir
elixir:
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 20.3
  - 21.3
  - 22.0
env: MIX_ENV=test
sudo: false
notifications:
email: false
before_script:
  - kerl list installations
script:
  - mix compile
  - mix test